CREATE ROLE USER_CLIENT LOGIN PASSWORD 'client' NOINHERIT;
CREATE ROLE AGENT LOGIN PASSWORD 'agent' NOINHERIT;


GRANT SELECT ON property, appointment, contract, property_review, agent_review TO USER_CLIENT;
GRANT INSERT ON client_appointment, agent_review, property_review, owner_review TO USER_CLIENT;
GRANT UPDATE ON client_appointment TO USER_CLIENT;
GRANT DELETE ON client_appointment TO USER_CLIENT;

GRANT SELECT ON client, owner, property, appointment, contract, agent_review, property_review TO AGENT;
GRANT INSERT ON property, appointment, contract TO AGENT;
GRANT UPDATE ON property, appointment, contract TO AGENT;
GRANT DELETE ON appointment, contract TO AGENT;




REVOKE ALL PRIVILEGES ON ALL TABLES IN SCHEMA public FROM AGENT;
REVOKE ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public FROM AGENT;
REVOKE ALL PRIVILEGES ON ALL FUNCTIONS IN SCHEMA public FROM AGENT;

REVOKE ALL PRIVILEGES ON ALL TABLES IN SCHEMA public FROM USER_CLIENT;
REVOKE ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public FROM USER_CLIENT;
REVOKE ALL PRIVILEGES ON ALL FUNCTIONS IN SCHEMA public FROM USER_CLIENT;